[package]
name = "two"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
heed = { version = "0.11.0", default-features = false, features = ["mdbx", "serde-json", "serde"] }
